### PR TITLE
Feature/ethereum support

### PR DESCRIPTION
**Pull request by 3ph**
@RootSoft I've added a new provider with basic Ethereum methods. I had to reorganise the code a bit as the abstract provider doesn't fit Ethereum methods. This seems to be similar to what other implementations do. Feel free to change that or suggest a different approach.

I would also update the README once we confirm the final implementation.

### CODE REVIEW

**Comment by RootSoft** [comment]
Thanks for the Pull Request @3ph !
Tested it out using metamask and got Ropsten working as well.
There's indeed not a 1-on-1 mapping between the different providers.

I've made some changes at the providers side:
* Removed `WalletConnectProviders`
* Removed `setCustomProvider`, `Algo` & `Eth` instances in favor of specifying your own provider / new implementations.
* Cleaned up the providers folder

Can you `Allow edits from maintainers.` so I can push the commit to your PR for review?
You can also check the branch here: https://github.com/RootSoft/walletconnect-dart-sdk/tree/ethereum

Please review it as well and let me know if there could be any improvements.

**Comment by jlalvarez18** [comment]
@3ph allow edits so we can get this going!! :)

**Comment by 3ph** [comment]
Hey @RootSoft. Sorry I was away. "Allow edits from maintainers" is already enabled though. 

I'll check out the branch tomorrow when I get a bit more organised.

**Comment by 3ph** [comment]
@RootSoft Checked out your branch, looks good! Are you able to push the commit here or do you want to merge your branch?

**Comment by RootSoft** [comment]
@3ph I've merged my branch with yours.
Another discord user is also testing it out later this week.
If no additional comments are made, I will publish a new version at the end of this week.

**Comment by akshay-bhimani-pedalsup** [comment]
Any example for signing transactions for Ethereum? I am not able to find can you share it here.

**Pull request merged**
